### ISSUE TITLE
Mock chat for App Store Screenshots

### ISSUE THREAD

**Issue by martindaum** [GetStream/stream-chat-swiftui#104]
## What are you trying to achieve?
We would like to script or mock a chat so we can use it for SwiftUI Previews as well as in UI tests for generating App Store Screenshots. Is this possible?

## If possible, how can you achieve this currently?
We could create a real channel and add the scripted messages and mocked users there. 

## What would be the better way?
We would prefer a locally mocked version, so we can also use mocked chats for Previews.

**Comment by martinmitrevski** [comment]
Hey @martindaum,

Thanks for asking the question. We are currently working on exposing our whole testing infrastructure to our customers.

It's still not completely done, but I think there's enough for your use-case, so you can already give it a go (otherwise, you can wait until we officially launch it).

Here are the details if you want to try it out:
1. In our main (low-level client) repo, we expose a package called `StreamChatTestTools`. This one contains mocks (mock chat client, mock controllers, etc). You can add this to your project get these mocks. For more details, please check our Package file: https://github.com/GetStream/stream-chat-swift/blob/develop/Package.swift.
2. There's another repo, where we keep our testing helpers, which can be beneficial too: https://github.com/GetStream/stream-chat-swift-test-helpers.
3. You can find examples on how to use the tools above in our snapshot tests in this repo. For example, here are the snapshot tests for the `ChatChannelView`: https://github.com/GetStream/stream-chat-swiftui/blob/main/StreamChatSwiftUITests/Tests/ChatChannel/ChatChannelView_Tests.swift. You can simulate different states in the channelController (e.g. messages)
```swift
       let controller = ChatChannelController_Mock(
            channelQuery: .init(cid: .unique),
            channelListQuery: nil,
            client: chatClient
        )
        let mockChannel = ChatChannel.mock(cid: .unique, name: "Test channel")
        var messages = [ChatMessage]()
        for i in 0..<15 {
            messages.append(
                ChatMessage.mock(
                    id: .unique,
                    cid: mockChannel.cid,
                    text: "Test \(i)",
                    author: .mock(id: .unique, name: "Martin")
                )
            )
        }
        controller.simulateInitial(channel: mockChannel, messages: messages, state: .remoteDataFetched)
```
4. Also, you can check our work on the `testing-strategy` branch, where we also use our `StreamChatTestMockServer` package, which is used to do e2e tests.

Hope this helps. 
Best,
Martin

**Comment by martindaum** [comment]
We don't need it right away, so I guess we can wait until it is officially launched! Looks exactly what we are looking for! Thank you!
