### ISSUE TITLE
Need access for `ChatMessage` in makeMessageAvatarView

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#160]
## What are you trying to achieve?
- I want to hide/unhide the user avatar base on the message type.

## If possible, how can you achieve this currently?
- I can't do that because `makeMessageAvatarView` has only access to `UserDisplayInfo`

## What would be the better way?
- Please help to add `ChatMessage` as well in makeMessageAvatarView factory function.
 So that I can add conditions based on the message type.

## GetStream Environment
**GetStream Chat version:** 4.19.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**Swift version:** 5
**Xcode version:** 13.4.1

**Comment by martinmitrevski** [comment]
Hey @ajay-simform,

We can't do this, since it will be a breaking change. Customers are relying on the exact method signature and parameters in `makeMessageAvatarView`.

In cases like this, where you need additional customizations for hiding the avatar, you can build your own message container view, by implementing the method `makeMessageContainerView` in the `ViewFactory`.

Hope this helps.
