### ISSUE TITLE
Can't navigate to existing chat that is below the fold from 'contact' list

### ISSUE THREAD

**Issue by jfru** [GetStream/stream-chat-swiftui#163]
## What did you do?
From the contact list, select an existing chat that is currently below the fold in the thread list
Note - these steps are not directly reproducible in the stream demo app because the new message composer doesn't actually navigate you to the chat. 

## What did you expect to happen?
Navigate into the chat

## What happened instead?
Navigates to thread list

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hey @jfru,

Can you please provide more details about this one? Not sure that I understand what's the issue.

Providing a video can also help.

Thanks,
Martin

**Comment by jfru** [comment]
https://user-images.githubusercontent.com/17079221/183470743-8303ab54-e295-45f9-a774-b913b6df6b35.MP4

Hey @martinmitrevski I'm adding a video here. This morning I noticed another issue which may have the same root cause... when I enter the app through a notification, if the chat is off the screen i.e. above the visible list of threads, then the chat doesn't open until you scroll up to the point in the list where it is located. Let me know if I should file a separate issue for this

**Comment by martinmitrevski** [comment]
Hey @jfru, @AndrewSB 

I've analysed this a bit, and it seems it's an issue in your app. While the dismiss animation is still ongoing, the navigation is triggered and there's clash with that animation. 

@AndrewSB I suggest adding a little delay with the deeplink (setting the selectedChannel after some time, e.g. 0.3s or similar). If that doesn't work, let's jump on a call, since I had trouble running your app (crashes on app start).

Similar fix might be needed for https://github.com/GetStream/stream-chat-swiftui/issues/171. I've noticed that you are not using the SDK's deeplinking functionality, but your own, with a hosting controller, which might be causing some issues.

Best,
Martin

**Comment by AndrewSB** [comment]
Hey @martinmitrevski, i just tested this with the delay, it didn't seem to have any effect on this issue

yeah https://github.com/GetStream/stream-chat-swiftui/issues/171 is basically the same issue. we did some analysis as well, our guess was that because the `NavigationLink` for the channel is inside a `LazyVStack`, the offscreen `NavigationLink`s aren't ready to be routed to until you scroll close to where the ChannelListItem is in the cell.
by moving that one level up, like so https://github.com/GetStream/stream-chat-swiftui/compare/main...saidReclip:stream-chat-swiftui:said/channel-navigation, the navigation seems to work, but i don't think this is the ideal solution.

are you available tomorrow, sometime between 9:30-11am PT? i can show you how this manifests, and you can share tips on how we could change deep linking into channels

**Comment by martinmitrevski** [comment]
hey @AndrewSB, I've sent an invitation for 11am PT, we will discuss this then.

**Comment by martinmitrevski** [comment]
Hey @AndrewSB,

Has the fix we did in our call solved this issue and https://github.com/GetStream/stream-chat-swiftui/issues/171? 

Please provide us feedback whether we can close these two.

Thanks,
Martin

**Comment by AndrewSB** [comment]
i believe we can close this out, but we're still doing some QA testing
