### ISSUE TITLE
Access the messages

### ISSUE THREAD

**Issue by wlopezvai** [GetStream/stream-chat-swiftui#184]
## What are you trying to achieve?
Hello, is there a way to access the messages list? I'm trying to filter some messages and hide or remove the ones that are from users that I muted or they muted me.

Thanks in advance.

**Comment by martinmitrevski** [comment]
Hey @wlopezvai,

The messages are available in the `ChatChannelViewModel`, which powers the `ChatChannelView`. One way to access them is to replace the channel view with your own custom view. You can do that via the `makeChannelDestination` in our `ViewFactory`.

Here's our default implementation: https://github.com/GetStream/stream-chat-swiftui/blob/main/Sources/StreamChatSwiftUI/ChatChannel/ChatChannelView.swift, you can build your own one with the same public sub-components we offer. Basically, instead of the default `viewModel.messages` on line 48, you can do some additional filtering. 

Note: this will still load all messages, you will just hide them in the UI. Filtering on a chat controller level with your custom criteria is not something we support at the moment.

Hope this helps,
Martin

**Comment by wlopezvai** [comment]
Thanks @martinmitrevski it worked creating a custom view, although I had to copy some files from the pod to my project
