### ISSUE TITLE
Support for audio recording

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#187]
## What are you trying to achieve?
- It would be good if we have the audio recording support that most chatting app has.

## If possible, how can you achieve this currently?
- streamChat doesn't support the audio recording feature atm

## GetStream Environment
**GetStream Chat version:** 4.20.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI

**Comment by martinmitrevski** [comment]
Hello @ajay-simform,

Thanks for the suggestion. We don't have immediate plans to add audio in the near future, but we already consider it in our roadmap.

Since this is a feature request, I've moved it to our Discussions page: https://github.com/GetStream/stream-chat-swift/discussions/2264.

Based on the interest of our community of users and our other priorities, we will look into this accordingly. 

Best, 
Martin
