### ISSUE TITLE
Swiping up in presented view, pulls the view down

### ISSUE THREAD

**Issue by rlindsey2** [GetStream/stream-chat-swiftui#227]
## What did you do?
Showed the ChatChannelView in a presented Navigation view, or just presenting the ChatChannelView directly.

## What did you expect to happen?
I expected the scrolling behaviour of the view to work as you'd expect on a mobile app. 

## What happened instead?
When you're in a ChatChannelView with no messages the view behaves as expected. When you pull down the view it pulls down. When you push up, the view tries to push up. 
However, when there are messages in the view, even just 1, when you pull down the view does nothing, but the weirdest thing is when you push up, the view pulls down! I've never come across this behaviour and completely stumped. It only happens with your ChatChannelView, none of our custom views. And the ChatChannelView behaves like normal if it's used in a fullScreenCover instead of a sheet. 

Check out the video below to see a full demo as it's very odd.

https://user-images.githubusercontent.com/37937966/199652988-e6c92bc5-b0b7-4549-8c9b-aff9bf249e2a.mov

## GetStream Environment
**GetStream Chat version:** 4.22.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.1
**Xcode version:** 14.1
**Device:** iOS 11 (happens on any)

**Comment by martinmitrevski** [comment]
Hey @rlindsey2,

Thanks for reporting. This is actually a known issue - it happens because the message list is an inverted scroll view and the gesture collides with the one from the native sheet. 

Since Apple doesn't provide a way to hook into navigation transitions with SwiftUI, unfortunately there's no way for us to fix this in the SDK.

Here are few alternatives to consider:
- use other form of presentation (push or full screen cover), as you've suggested.
- use UIKit navigation with hosting view controller and a root SwiftUI view, to present the chat. In this case, you would need to set the navigation transition to our `StreamModalTransitioningDelegate`, as described here: https://github.com/GetStream/stream-chat-swift/issues/1307#issuecomment-1028036153.
- if that's not possible with your app architecture, and this is a deal breaker for you, you might consider using our UIKit SDK - with the custom navigation transition as described above.

When/if Apple exposes a way to hook into navigation transitions in SwiftUI, we will provide a fix in the SwiftUI SDK accordingly.

Hope this helps,
Martin

**Comment by rlindsey2** [comment]
Hey Martin - I appreciate the quick response! Thanks for the explanation and although it's sad to hear - I'm glad I'm not going crazy. Our app if pure SwiftUI so I don't think we will be able to go with the second suggestion. Or at least I'm assuming it's only possible to do use that setup when you have base UINavigation controllers?

We may have to stick with keeping it as full screen for now. On your last point - if this a super low priority for you, and likely to be 12+ months away if at all?

**Comment by martinmitrevski** [comment]
Hey @rlindsey2,

Yes, if you are using pure SwiftUI, it's best to go with full screen cover or push. The other approaches are possible only with UINavigationControllers.

About the priority, it's actually not a low priority for us. The issue is that, at the moment, there's no safe way to fix this with Apple's SwiftUI SDK, since it doesn't allow us to hook into navigation transitions (and fix it like in UIKit). We're following every SwiftUI release for limitations like this, and if something comes up, we will provide a fix. However, that won't be available for older versions sadly.

If you have any ideas how to approach this in a different way, we're always open to suggestions.

Best,
Martin
