### ISSUE TITLE
Including a `struct MessageDisplayInfo` disables factory's makeMessageContainerView

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swiftui#23]
got an interesting one. check this out

https://user-images.githubusercontent.com/3814772/153355547-6c8fafe6-1b97-47f4-a2d9-419e0e92905f.mov

uncommenting that `struct MessageDisplayInfo` makes it so the custom `makeMessageContainerView` i have in my `ViewFactory` stops taking effect. kind of wild, right? it's not doing a default registration or anything like that.

i'm doing this because i need to hide the delivery indicators and message timestamps from the message containers. going to email you a copy of the project, it's very hello world-y

**Comment by martinmitrevski** [comment]
The issue here is that `MessageDisplayInfo` is a public struct from our SDK. If you create a new one with the same name, that one goes into the signature of the `makeMessageContainerView`, so the method of the SDK is not implemented anymore - therefore it returns the default message container. 

If you want to define a struct with the same name, you can just update the signature method to explicitly say that you are using the `StreamChatSwiftUI.MessageDisplayInfo` from our SDK (although I don't think you need this, better to delete it):
```
func makeMessageContainerView(
        channel: ChatChannel,
        message: ChatMessage,
        width: CGFloat?,
        showsAllInfo: Bool,
        isInThread: Bool,
        scrolledId: Binding<String?>,
        quotedMessage: Binding<ChatMessage?>,
        onLongPress: @escaping (StreamChatSwiftUI.MessageDisplayInfo) -> (),
        isLast: Bool
    ) -> some View
```
Btw, if you just need to disable the read indicators (and you are ok with the rest of the design), you can just disable them from the Stream dashboard for your app - it will be automatically reflected in the SDK. We can expose a similar thing with the timestamps. 

If you need more customizations apart from these, then creating custom message container is the preferred way.

**Comment by AndrewSB** [comment]
got it, let me try from within the dashboard instead
