### ISSUE TITLE
ChatMessageView scrolls the sheet itself when used inside of a sheet

### ISSUE THREAD

**Issue by grandsir** [GetStream/stream-chat-swiftui#253]
## What did you do?
I'm trying to present a ChatChannelList inside of a sheet to make my app easy to use

## What happened instead?
A weird bug happened with a terminal output saying "ScrollViewPreferenceKey" tried to update multiple frames...  

## GetStream Environment
**GetStream Chat version: Latest**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version: Tried with iOS 14.0, 14.2, 15.1, 16.1**
**Swift version: 5.7**
**Xcode version: 14.2**
**Device: Tried with 14 Pro max, 13 Pro, 11,  XR, 6s, 7**

## Additional context
https://user-images.githubusercontent.com/69051988/209098026-a9388617-1fa1-40d9-ad10-07141cf73f8d.mov

**Comment by martinmitrevski** [comment]
Hello @grandsir,

Thanks for reporting. This is a known issue, that was reported few times, e.g. https://github.com/GetStream/stream-chat-swiftui/issues/227. 

However, this can be only fixed by hooking into the navigation transitions, which is not supported by SwiftUI. Therefore, we officially don't support using a sheet from our SwiftUI SDK. We recommend using either fullScreenCover, push navigation or using our UIKit SDK instead.

As soon as Apple provides more control for this, we will fix it in the SDK.

Best,
Martin
