### ISSUE TITLE
Wrong scroll position after message is deleted

### ISSUE THREAD

**Issue by mdhanif-simformsolutions** [GetStream/stream-chat-swiftui#254]
## What did you do?
Send a long message with multiple videos attached in it.

## What did you expect to happen?
After deleting message it should stay at the position of the message.

## What happened instead?
After deleting message scroll offset has been changed a little.

## GetStream Environment
GetStream Chat version: 4.25.0
GetStream Chat frameworks: StreamChatSwiftUI
iOS version: 16.2
Xcode version: 14
Device: iPhone Xs Max

## Additional context
Video ref :- [Delete message scroll issues](https://drive.google.com/file/d/1R8sEuFv5bnrqxdiy2QhpcckJyNQ6czOs/view?usp=share_link)

**Comment by martinmitrevski** [comment]
Hi @mdhanif-simformsolutions,

This behaviour is expected, since the whole large area of videos is replaced with the small indicator that the message is deleted. The message list starts from the bottom and grows to the top, and we can't do anything in particular to prevent it from moving when there are that big messages.

Best,
Martin
