### ISSUE TITLE
QueryChannels failed with error: \"stream-auth-type missing or invalid\"

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#260]
Receiving this error log frequently in the console. What does it mean?

```
[ERROR] [com.apple.NSURLSession-delegate] [RequestDecoder.swift:67] [decodeRequestResponse(data:response:error:)] > API request failed with status code: 401, code: 5 response:
{
  "code" : 5,
  "message" : "QueryChannels failed with error: \"stream-auth-type missing or invalid\"",
  "details" : [

  ],
  "more_info" : "https:\/\/getstream.io\/chat\/docs\/api_errors_response",
  "StatusCode" : 401,
  "duration" : "0"
})
```

## GetStream Environment
**GetStream Chat version:** 4.25.0
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** 15.7
**Swift version:** 5
**Xcode version:** 14.2
**Device:** Iphone-X

**Comment by martinmitrevski** [comment]
Hello @ajay-simform,

It means that your token expired and the channel list wasn't loaded. Afterwards, most likely the token got refreshed and the channel list was loaded. You should make sure the channel list view is not shown before you have a valid token in order to not have this error.

See also: https://github.com/GetStream/stream-chat-swift/issues/2431.

Best,
Martin
