### ISSUE TITLE
ChannelList performance issue

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swiftui#263]
- Channel list view takes much CPU and downgrades performance.
- I observed that chatChannelListView takes much CPU while it is loading.
- I want to show multiple channel lists with different queries.
- For that, I just wrapped chatChannelListView with swiftUI default TabBarView and change the index.
- You can see in the attached video, the CPU usage is at peak level and the UI doesn't respond.
- I need your help to optimise CPU performance.

## GetStream Environment
**GetStream Chat version:** 4.25.0
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** 16.x
**Swift version:** Swift 5
**Xcode version:** 14.2
**Device:** Iphone_X

## Additional context

https://user-images.githubusercontent.com/47667077/212083704-c4e77ac0-1cc4-456f-9024-3149c7595af3.mov

**Comment by martinmitrevski** [comment]
Hey @ajay-simform,

Can you share some example code how are you doing this? I'm not able to reproduce this with our demo app, so it's most likely something with your integration.

Best,
Martin

**Comment by ajay-simform** [comment]
Hey @martinmitrevski ,
- I have tested with the user which has 90 channels. I suggest please don't test with the demo users.
- This is the example code [link](https://drive.google.com/file/d/17R9xX6YThtm6QNXDM3ug1LyAGZP8ImiV/view?usp=sharing) with integrating TabBar with ChannelListing.

Thanks

**Comment by martinmitrevski** [comment]
Hey @ajay-simform,

I've tried your code. So, you're trying to load all channels at ones, which of course takes more memory.

I have two suggestions for you:
- one option is to not use `TabView`, but use if statements to switch between the channels. This will deallocate the channel lists that are currently not shown on screen, and you will save up a lot on memory. Sth like this will work
```swift
if selectedTab == 1 {
    ChannelList1()
} else if selectedTab == 2 {
    ChannelList2()
}
```
- if you want to stick to your approach, you will need to reduce the number of channels that you load. You can use the `ChannelListQuery` and load for example 10 channels instead of 20. Also, you can also reduce the messages loaded per channel, so instead of loading 25 messages, you can use `messagesLimit` in the same `ChannelListQuery` and load for example 5-10 messages initially.

However, the first option is much better, you don't really need a `TabView` for this use case. SDK-wise, we can't do much, since it's actually a lot of content (90 channels x 25 messages) and it's expected that there's increased memory usage.

Hope this helps.
