### ISSUE TITLE
Getstream default search component fails with response 400

### ISSUE THREAD

**Issue by grandsir** [GetStream/stream-chat-swiftui#266]
## What did you do?
Let me clear this thing first, I didn't do anything to the default component. I created a room in the getstream interface called "testroom" and searched for "text" in the search bar, and nothing showed up.

Note: we tested it on an account that has almost 30 available chats but it didn't work either. Nothing showed up.

## What did you expect to happen?
Getstream to return search result

## What happened instead?
failed

## GetStream Environment
**GetStream Chat version: Latest**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version: 14.0**
**Swift version: 5.7**
**Xcode version: 14**
**Device:iPhone  11(same on every device)**

## Additional context
![Screenshot_2023-01-18_at_02 42 00](https://user-images.githubusercontent.com/69051988/213122723-960f8467-30ef-4cc7-95fe-2ae3325a85ce.png)

**Comment by martinmitrevski** [comment]
Hey @grandsir,

The default search in the SDK searches messages with a certain text, not the channel names. So for example, if you have a channel named "testroom", and you search for "test", nothing will be returned. If you have a message called "testroom" though, that message will be returned as a search result, together with the channel it belongs to.

That's the default and expected behaviour. If you want to have channel search by name, you can use method `func makeChannelListTopView(searchText: Binding<String>)` in our `ViewFactory` and provide a different implementation.

Hope this helps,
Martin

**Comment by grandsir** [comment]
Hey @martinmitrevski, thanks for your reply.

Unfortunately, that does not work too.
https://user-images.githubusercontent.com/69051988/213139795-059dc820-7a48-42cc-afca-7cae2e8601e7.mov

**Comment by martinmitrevski** [comment]
ok, we will need to do some troubleshooting then:
- can you please make sure that search is turned on for your corresponding channel type? It seems you're using `livestream`, and search is by default off there (attached a screenshot for more context).
- can you please try reproducing this in our demo app?
- can you share some customizations that you have done with the SDK?

My assumption is that it's the first one. However, if not, might be good to also share some reproducible sample project to look at.

![Screenshot 2023-01-18 at 11 10 21](https://user-images.githubusercontent.com/2971717/213144870-d350a0b9-640f-484f-8bac-818699eedf71.png)

**Comment by grandsir** [comment]
Oh, yeah enabling search did work. You guys know your product well. Thanks!
