### ISSUE TITLE
Getstream inside NavigationView sometimes acts buffy

### ISSUE THREAD

**Issue by grandsir** [GetStream/stream-chat-swiftui#268]
## What did you do?
in our app, I just switched to getstream tab

## What did you expect to happen?
getstream to work properly

## What happened instead?
Sometimes, it works just fine. But sometimes, I get an error in the terminal saying:
<img width="885" alt="Screenshot 2023-02-02 at 10 29 19" src="https://user-images.githubusercontent.com/69051988/216264500-66640ffb-5a0b-4ea9-b7a3-033328fc00e6.png">
but i did not disable embedInNavigationView when building chatChannelListItem, but still sometimes seeing this error though

but gets fixed after i switch to a tab and go back

## GetStream Environment
**GetStream Chat version: latest**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version: ios 16.1 (issue can be related to ios version)**
**Swift version: latest**
**Xcode version:14**
**Device:iPhone 11**

## Additional context

https://user-images.githubusercontent.com/69051988/216264032-f32675c5-44dd-4090-9369-b2f679ef996d.mov

**Comment by martinmitrevski** [comment]
Hi @grandsir,

Can you please share more details about how are you integrating the channel list view? Do you already have a parent navigation view on top of which you add Stream's view?

A sample code would also help.
Thanks,
Martin

**Comment by grandsir** [comment]
hey @martinmitrevski Yes, there is a parent NavigationView that we use in our CustomTabView
![Screenshot 2023-02-03 at 15 30 00](https://user-images.githubusercontent.com/69051988/216607747-56f49fd5-a60c-432d-89a0-7947b1d68782.png)
![Screenshot 2023-02-03 at 15 47 42](https://user-images.githubusercontent.com/69051988/216607980-508cadf0-3e7f-40f9-9357-b41e2ee71892.png)


But I'm not sure these would help you, because this issue has existed since we started implementing getstream. One additional piece of info would be that this bug doesn't occur in iOS 14. But occurs in iOS 15 and 16.

Also we're developing our app for iOS 14 and using SwiftUI 2.0.

and we implement ChannelListItem like this:
```swift
    func makeChannelListItem(
        channel: ChatChannel,
        channelName: String,
        avatar: UIImage,
        onlineIndicatorShown: Bool,
        disabled: Bool,
        selectedChannel: Binding<ChannelSelectionInfo?>,
        swipedChannelId: Binding<String?>,
        channelDestination: @escaping (ChannelSelectionInfo) -> ChatChannelView<CustomFactory>,
        onItemTap: @escaping (ChatChannel) -> Void,
        trailingSwipeRightButtonTapped: @escaping (ChatChannel) -> Void,
        trailingSwipeLeftButtonTapped: @escaping (ChatChannel) -> Void,
        leadingSwipeButtonTapped: @escaping (ChatChannel) -> Void
    ) -> some View {
        ZStack {
            NavigationLink(tag: channel.channelSelectionInfo, selection: selectedChannel) {
                channelDestination(channel.channelSelectionInfo)
            } label: {
                EmptyView()
            }
            
            Button {
                onItemTap(channel)
            } label : {
                CustomChannelListItem(channel: channel) // I don't think you want to know what's in there
            }
        }
    ```

**Comment by martinmitrevski** [comment]
Hey @grandsir,

Thanks for sharing the additional details. One thing I've noticed is that you are not setting an id for the channel list items, which might be causing the issue. 

Without the id modifier, SwiftUI might decide to redraw the view with the navigation link, since it might not have enough info about its identity. 

Can you please try that? Adding something like `.id("\(channel.id)-listitem")` at the end of your `ZStack` should be enough.

Let me know if that helps or we should do some more troubleshooting.
Best,
Martin

**Comment by grandsir** [comment]
No luck @martinmitrevski 😔

**Comment by martinmitrevski** [comment]
Ok, might be some collision with your app structure.
 
Another approach that you could try is:
- remove the `NavigationLink` from the `makeChannelListItem`
- add only one `NavigationLink` at the place where you keep the `ChatChannelListView` (either as a background, or in a `VStack`)
- the new `NavigationLink` can depend on `isActive`, instead of `tag` / `selection`, and the `isActive` state would be a new @State in your parent view.
- you will update the `isActive` state by listening to the `onReceive` of the `selectedChannel` from the `ChatChannelListViewModel` (that you can instantiate outside the view and inject it in the `ChatChannelListView`).

Something like this:
```swift
ChatChannelListView(...)
        .background(
                NavigationLink(isActive: $isActive, destination: {
                    if let selectedChannel = viewModel.selectedChannel {
                        viewFactory.makeChannelDestination()(channelSelectionInfo)
                    } else {
                        EmptyView()
                    }
                }, label: {
                    EmptyView()
                })
            )
```
Let me know if that helps. If not, please send me a minimal reproducible sample project with the issue, and we will look into it.

**Comment by grandsir** [comment]
that didn't help either, but building a custom ChannelList solved the problem. not sure what's the issue
