### ISSUE TITLE
Spacing issue with MessageList // Composer within a TabView

### ISSUE THREAD

**Issue by kmkarim** [GetStream/stream-chat-swiftui#277]
## What did you do?
Currently have a MessageList embedded within a TabView:

TabViewWrapper
`TabView(selection: $tabIdx) {
            ChatView().tabItem{
                if tabIdx == 0 {
                    Image("matches_active")
                } else {
                    Image("matches")
                }
                Text("Matches")
            }
                .tag(0)
        }`

ChatView
`
    var body: some View {
        NavigationStack {
            ChatChannelListView(viewFactory: CustomFactory.shared, handleTabBarVisibility: false, embedInNavigationView: false)
            .navigationDestination(for: ChatChannel.self) { value in
                VStack {
                    CustomFactory.shared.makeChannelDestination()(value.channelSelectionInfo)
                }
                //.padding(.bottom, 1)
            }
        }
    }
`

If there is no bottom padding, the composer lands behind the Tab bar with the following effect (See Screenshot):
![IMG_1936](https://user-images.githubusercontent.com/101993/219551050-267161c1-5cd7-41c7-b400-266a9305482a.jpg)

With a padding of 1 its to high (See Screenshot)
![IMG_1937](https://user-images.githubusercontent.com/101993/219551072-f82d13ea-a90b-423c-bbfa-ef986770fc74.jpg)

## What did you expect to happen?
Expected the composer to be flush against the top of the tab bar

## GetStream Environment
**GetStream Chat version:** 4.26.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.1
**Swift version:** Swift 5
**Xcode version:** 14.0.1
**Device:** iPhone 14 Pro

**Comment by martinmitrevski** [comment]
Hi @kmkarim,

Thanks for reporting this. I can confirm it's an issue if you turn off the default tab bar handling and use the new navigation API.

We have fixed this and it's now available in our `main` branch. The fix is to allow turning off the default tab bar handling for the message list as well (they are two standalone components).

Therefore, you will need to update your `MessageListConfig` with the newly introduced property `handleTabBarVisibility`. The default value is `true`, you should set this to `false`.

Hope this fixes your issue.
Best,
Martin

**Comment by martinmitrevski** [comment]
This is fixed and released with the latest version, 4.27.0.
