### ISSUE TITLE
When switching between text-input and image-picker, the keyboard shouldn't animate

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-swiftui#28]
https://user-images.githubusercontent.com/97132583/153683204-1497b77e-1602-4525-bb6b-4f1c5fe2ae4a.mp4

## What are you trying to achieve?
See a comparison between Stream and Signal. First part of the video is Stream and the second part is Signal.

In Signal, when you open the inline image-picker, the keyboard doesn't shift or animate. This is the standard behavior across most messaging apps.
In UIKit world, you can accomplish it by using UITextField.inputView

## If possible, how can you achieve this currently?
I guess I'll just have to write my own custom composer ...

## What would be the better way?
StreamChatSwiftUI can use UITextField.inputView for the image picker.

**Comment by martinmitrevski** [comment]
Hi @linhewinner, 

Thanks for the interesting observation. Since this SDK is in SwiftUI, your suggestion to use `UITextField.inputView` would not be very feasible, since it would mean that the whole composer attachments logic would need to be implemented in UIKit, and this is not something that we want to do (we already have an iOS UIKit SDK). 

The SwiftUI text field component is limited in this regard and actually the animation looks nice here (at least in my opinion).

I'm closing this issue. If the native SwiftUI `TextField` or `TextView` component have more capabilities in the future, we can revisit this and maybe make a config to turn off the animation.

Best, 
Martin

**Comment by tr736-reclip** [comment]
I second this and would like to see no animation between swapping from keyboard to image picker.
