### ISSUE TITLE
Animation of messages being sent

### ISSUE THREAD

**Issue by bobakemamian** [GetStream/stream-chat-swiftui#302]
## What did you do?
When I send a message, the message bubble displays behind the last message sent, and then the last message animates above it.

Here is a video example:

https://user-images.githubusercontent.com/836531/231674309-ff18b122-f344-476c-b7c7-d30e2d2fe2c0.mp4

Here is a slow-mo version:

https://user-images.githubusercontent.com/836531/231676130-d9ee171e-60d1-4d1a-9503-daeaaeaeac87.mp4

Slowing it down, here are screenshots of the transition:

<img width="287" alt="CleanShot 2023-04-13 at 02 34 21@2x" src="https://user-images.githubusercontent.com/836531/231674368-3efebb10-a216-41c6-97bd-12d6a3614132.png">
<img width="255" alt="CleanShot 2023-04-13 at 02 34 34@2x" src="https://user-images.githubusercontent.com/836531/231674392-8e5ef3d3-70ae-43bf-b89e-0236f4944240.png">
<img width="239" alt="CleanShot 2023-04-13 at 02 34 42@2x" src="https://user-images.githubusercontent.com/836531/231674402-900f72ae-5b9b-4f5c-89d3-ce1bc01e418a.png">

## What did you expect to happen?
When I send a message, the message bubble should push the older messages bubbles up at the same pace it enters the view.

Here is a video example of expected animation:

https://user-images.githubusercontent.com/836531/231676273-40529a34-bb3a-4f58-ae54-a3aedb5d6a05.MP4

Here is a slow-mo example:

https://user-images.githubusercontent.com/836531/231675689-2ee34b4b-c501-4f14-a85b-b6da2c67b0c0.mp4

## What happened instead?
The new message bubble fades in behind the old bubble:

<img width="287" alt="CleanShot 2023-04-13 at 02 34 21@2x" src="https://user-images.githubusercontent.com/836531/231675372-99fa49a2-f0e6-4c1f-9abf-66914fca7d78.png">

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.4
**Swift version:**
**Xcode version:** 14.3
**Device:** iPhone 14 Pro

**Comment by martinmitrevski** [comment]
Hi @bobakemamian,

The default transition that we have when a new message is received is `.identity`. Since there are many different ways how this can be animated, we let our customers to add their custom transitions.

You can find more details here: https://getstream.io/chat/docs/sdk/ios/swiftui/message-components/message-display-options/. Basically, you will need to add a custom transition for `currentUserMessageTransition` (for the current user's messages) and `otherUserMessageTransition` (for the other user's messages) in the `MessageDisplayOptions`, part of the `MessageListConfig`.

If you want it like Apple Messages, I guess you will need to animate from the middle of the screen, towards the trailing part.

Hope that helps.
Best, Martin

**Comment by bobakemamian** [comment]
Thank you, will give it a try!
