### ISSUE TITLE
Channels list not updating in iPad when message came

### ISSUE THREAD

**Issue by muhammadabbas001** [GetStream/stream-chat-swiftui#333]
## What did you do?
We implemented Stream Chat SDK in our app. It's working fine on iPhone but on iPad, ChannelList is not updating when the message came. 

## What did you expect to happen?
ChannelList should update when a new message came.

## What happened instead?
ChannelList is not updating on iPad.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hey @muhammadabbas001,

By default, the channel list is not updated when a chat view is active.

In order to change that, you need to update the value `updateChannelsFromMessageList` in the `MessageListConfig` to true (you can also check if the device is iPad if you need this behaviour only there).

Hope this helps, Martin
