### ISSUE TITLE
VideoAttachmentContainerView does not honour `makeMessageViewModifier`.

### ISSUE THREAD

**Issue by chan-reclip** [GetStream/stream-chat-swiftui#336]
I noticed my custom `MessageViewModifier` doesn't apply to message with video attachment.

Because the following line doesn't honour `makeMessageViewModifier`: https://github.com/GetStream/stream-chat-swiftui/blob/32db431a4cc8dfce837ffddaa39701f675c85728/Sources/StreamChatSwiftUI/ChatChannel/MessageList/VideoAttachmentView.swift#L55

It should create `MessageViewModifier` via `viewFactory` instead.

I assume this problem exists in other places where `View.messageBubble(...)` is used.

**Comment by martinmitrevski** [comment]
Hey @chan-reclip, 

Yes, the bubbles are not generic over the ViewFactory at the moment. We will try to improve that in the future, if there are no breaking changes.

In the meantime, you can also implement the video attachment view by yourself, since all the building blocks are public.

Best, Martin

**Comment by martinmitrevski** [comment]
Hey @chan-reclip,

This is now fixed on our `main` branch, and it will be included in the next release.

Best, Martin

**Comment by chan-reclip** [comment]
@martinmitrevski Thanks!
