### ISSUE TITLE
Clear input field on custom send message

### ISSUE THREAD

**Issue by joe-donino** [GetStream/stream-chat-swiftui#350]
We are overriding makeComposerInputView in the ViewFactory and implementing a custom send button action by using  chatClient
                    .channelController(for: channelId)
                    .createNewMessage()
                    
We can clear the composer input field text by setting the wrapped value to "", however there doesn't appear to be a way to clear the composer input field of attachments like images. Can you please advise how to do this? Our overall goal is to be able to intercept a message text before it is sent, so if there is a better way to do this please let me know?

**Comment by martinmitrevski** [comment]
Hi @joe-donino,

In the `ComposerConfig`, there's a closure `adjustMessageOnSend`, which adjusts the text message before it's sent. You can provide your own implementation as needed, and use our default flow, which clears all the data.

Otherwise, we don't allow clearing attachments from the outside. 

Hope that helps.
Best, Martin
