### ISSUE TITLE
Create Group of Channels

### ISSUE THREAD

**Issue by muhammadabbas001** [GetStream/stream-chat-swiftui#373]
## What did you do?

1. Is there a way for a user to create a channel in such a way that the channel is only visible to the creator and not to any other members?
2. Is there a way to create a group of multiple channels, and within this group, those channels are being displayed?

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
1. It is possible if you know the creator id in advance, you could do something like `.containMembers(userIds: [creatorId])`. Otherwise, if you don't know it in advance, it's not possible.
2. Yes, you can do this with different query filters. You can either group them by existing values or extra data values. Check this guide on instructions how to do this: https://getstream.io/chat/docs/sdk/ios/client/controllers/channels/.
