### ISSUE TITLE
MessageActions do not respect custom icons

### ISSUE THREAD

**Issue by martindaum** [GetStream/stream-chat-swiftui#377]
## What did you do?
I'll updated all icons in the Images struct to use SFSymbols instead of custom icons. I did discover that custom icons for message actions are not used. The Message actions do use hardcoded icon names in the code (e.g. "icn_copy")

## What did you expect to happen?
The overwritten icons should be used instead the default icons

## What happened instead?
The default icons are shown

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hi @martindaum,

Thanks for reporting. We are aware of this limitation, but we are not able to change it at the moment, since it requires breaking public API changes. We will fix it in a next major version release.

In the meantime, the recommended way with the 4.x versions is to create your own list of message actions, via the factory method `supportedMessageActions`.

Hope that helps, 
Martin
