### ISSUE TITLE
How to hide search bar and disable chat swipe gesture?

### ISSUE THREAD

**Issue by JayMehta97** [GetStream/stream-chat-swiftui#38]
I tried to find this query in the official documentation and also went through the SDK options but couldn't find a simple way to do this. We have similar customization in Android and there it is very simple to hide search bar and disable chat swipe gesture.

**Comment by martinmitrevski** [comment]
Hey @JayMehta97, 

Thanks for asking the questions. We will update the docs in the next release to be more specific about these two use-cases. 

About hiding the search bar, you need to return `EmptyView` from the method `makeChannelListTopView` in your custom view factory. It's described in more details at this page: https://getstream.io/chat/docs/sdk/ios/swiftui/components/helper-views/.

About disabling the swiping, you need to implement the `makeChannelListItem` (also described on the same page) and just not wrap the cell in a swipeable list item. Here's an example how to do that:

```swift
public func makeChannelListItem(
        channel: ChatChannel,
        channelName: String,
        avatar: UIImage,
        onlineIndicatorShown: Bool,
        disabled: Bool,
        selectedChannel: Binding<ChannelSelectionInfo?>,
        swipedChannelId: Binding<String?>,
        channelDestination: @escaping (ChannelSelectionInfo) -> ChannelDestination,
        onItemTap: @escaping (ChatChannel) -> Void,
        trailingSwipeRightButtonTapped: @escaping (ChatChannel) -> Void,
        trailingSwipeLeftButtonTapped: @escaping (ChatChannel) -> Void,
        leadingSwipeButtonTapped: @escaping (ChatChannel) -> Void
    ) -> some View {
        return ChatChannelNavigatableListItem(
            channel: channel,
            channelName: channelName,
            avatar: avatar,
            onlineIndicatorShown: onlineIndicatorShown,
            disabled: disabled,
            selectedChannel: selectedChannel,
            channelDestination: channelDestination,
            onItemTap: onItemTap
        )
    }
```

Let us know if we can help with anything else. 

Best, 
Martin

**Comment by JayMehta97** [comment]
Hey @martinmitrevski, thanks a lot!

Both the code blocks you shared have addressed both my doubts. Here are few more questions (Don't know whether should I create different issue for this or not)

1. How to just hide `subTitle` view of ChatChannelHeaderView for selective chats.
Issues I faced while trying to achieve this:
- I copied `DefaultChatChannelHeader` code block and tried creating custom channel header but couldn't as `currentlyTypingUsersFiltered`, `typingIndicatorPlacement` and `onlineInfoText` are inaccessible due to 'internal' protection level.
- In the  documentation, there is an example for creating `CustomChatChannelHeader` in which it has `onlineInfoText` but when I copy the same code block in my app it gives inaccessible due to 'internal' protection level error. - https://getstream.io/chat/docs/sdk/ios/swiftui/components/channel-header 
- In the documentation for channel header, at multiple places it mentions `ChannelHeaderViewModifier` but I think it has been renamed to `ChatChannelHeaderViewModifier` as I couldn't find any `ChannelHeaderViewModifier` in SDK code.
- I also wanted to conditionally use either `DefaultChatChannelHeader` or `CustomChatChannelHeader` depending on channel type but I couldn't as `DefaultChatChannelHeader`'s `init` is inaccessible due to 'internal' protection level.

- Android Stream SDK has `messageListHeaderView.hideSubtitle()` for this.

2. How to change text color of other user's message only?

3. Wanted to know reason why for default reaction assets the SDK uses `PDF` instead of image resource and what should we use for our custom reaction assets.

4. How to hide navigation bar only for the channel list screen and not for message list screen. In Android we have this customisation as it has the channel list (Recylcer view / Table view) as an independent component

5. If a message in a channel has been viewed by few members then can we get that information? Similar to `Info` in `Whatsapp` 


Let me know if you need more details for any of the above points.

Thanks.

**Comment by martinmitrevski** [comment]
hey @JayMehta97,

Thanks again for your questions and comments. Hope this helps:
1. You are right about the internal methods. It makes sense for them to be public, so now they are available as public on `main`, so you can start using them now if you are pointing to the main branch. Otherwise, this will be released next week with the 4.13.0. This applies to the initalizer of the DefaultChatChannelHeader, as well as the onlineInfo method.
- With that, you can easily switch between those based on a certain condition:
```swift
public func body(content: Content) -> some View {
        content.toolbar {
            someCondition ?
                DefaultChatChannelHeader(
                    channel: channel,
                    headerImage: channelHeaderLoader.image(for: channel)
                )
            :
                CustomChatChannelHeader(
                    channel: channel,
                    headerImage: channelHeaderLoader.image(for: channel)
                )
        }
}
```
- You are also right about the docs, I've updated them, and this will be publicly available with the next release. Thanks for that! 
- Looking forward to your feedback. If you need anything else about the header, let's proceed the discussion in a new issue.

2. How to change text color of other user's message only?
This is not possible at the moment (only the background can be changed for the other user). There are two options here - either you can create a separate issue for this and we will expose it soon. Or, you can implement the `makeMessageTextView` and change the color there. However, with the second option, you will also need to update the other related attachment creation methods that support text too, so if you support attachments, it's best to go with the first option.

3. We are using PDFs for easier scaling of images in multiple resolutions. But, that doesn't prevent you from using anything else, like pngs (you can use anything that's supported by assets here).

4. We also have an independent component for the channel list, that you can use in order to control the navigation bar. It's called `ChannelList` and you can see an example here: https://github.com/GetStream/stream-chat-swiftui/blob/main/DemoAppSwiftUI/iMessagePocView.swift.
Potentially, you will need to hook to the method that presents the message list and control the navigation bar display there, so the method `makeChannelDestination` might be useful here.
Curious to know how this will work for you, if you have some trouble, feel free to create a separate issue.

5. Yes, this is possible. For every `ChatChannel`, there's a `reads` property, which is an array of `ChatChannelRead`. In here, you have info about the `lastReadDate` and `user`. For a particular message, you just need to compare it's date with this `lastReadDate`. We have an example with the read indicators here (`readUsers` method): https://github.com/GetStream/stream-chat-swiftui/blob/main/Sources/StreamChatSwiftUI/ChatChannel/Utils/ChatChannelExtensions.swift 

I hope I've covered everything with your questions. If not, please let me know and I'll provide further clarifications. 

Best,
Martin

**Comment by martinmitrevski** [comment]
Hey @JayMehta97,

update on 2. This is now possible on our main branch by changing the `messageOtherUserTextColor` in our colors pallete. More on changing colors here: https://getstream.io/chat/docs/sdk/ios/swiftui/getting-started/. For the current user, it's `messageCurrentUserTextColor`.

**Comment by JayMehta97** [comment]
Hi @martinmitrevski ,

Thanks for all the help. Really appreciate your quick responses.

- Changes that have been done regarding ChatChannelHeader has resolved my issues.

- I am yet to try your given update on 2, 4 and 5 but will let you know once I try them.

There were a few questions I have regarding using token provider:

1. As we are using tokens with expiration time so I created a `TokenProvider` as explained here - https://getstream.io/chat/docs/ios-swift/tokens_and_authentication/?language=swift . With `TokenProvider` I thought that now at no place I will have to manually pass token and SDK will take care of generating it even for the first time but the SDK requires us to pass a token manually in `connectUser` method. So now I have to first manually execute `chatClient?.tokenProvider` and then in its completion call the `chatClient?.connectUser` method with the generated token. Please let me know if I have missed or done something wrong here or is my understanding and steps correct.

2. [Not really related to SDK, might be a code concept issue from my side] We have created a different module for chat which uses Stream SDK and we integrate the private chat module in our app using SPM. So our implementation for `TokenProvider` looks like this:

Chat module code:

```
public func setup(apiKey: String, tokenProvider: @escaping ((Bool, String?) -> Void) -> ()) {
    var config = ...
    ChatClient.shared = ChatClient(config: config) { completion in
        tokenProvider { isSuccess, userToken in
            if let userToken = userToken, isSuccess {
                do {
                    let token = try Token(rawValue: userToken)
                    completion(.success(token))
                    return
                }
                catch let err {
                    print(err)
                }
            }
            completion(.failure(TokenError.failedToGetStreamToken))
        }
    }
}
```

This is how we call the `setup` function from our app and this is where I facing an issue:
```
Chat.shared.setup(apiKey: Constants.Stream.apiSecret) { completion in
    // Getting compile time error `Escaping closure captures non-escaping parameter 'completion'` for below line. I do understand why it giving the error and what it means but not able to solve it. Can you help me here?
    self.getChatToken { isSuccess, token in
        completion(isSuccess, token)
    }
}
```

Overview of `getChatToken`
```
func getChatToken(completion: @escaping (Bool, String?) -> Void) {
    NetworkingLayer.getChatToken() { token in
        completion(true, token)
    }
}
```


3. I wanted to enable and disable selective message options from the default message options depending on a custom condtion, very similar to the example shown here - https://getstream.io/chat/docs/sdk/ios/guides/customize-message-actions but in this example it uses `ChatMessageActionsVC` which I couldn't find the SDK so I am missing something here?

Let me know if you need more details for any of the above points.

Thanks.

**Comment by martinmitrevski** [comment]
hey @JayMehta97,

1. About the tokens, the flow goes like this:
- the method  `connectUser` needs to be called initially (after you login the user in your app). This method sets up the chat client with that particular user.
- the token provider closure in the chat creation method is called only when a token is expired and needs to be refreshed.

So the difference here is that in the first case the user logins into to the app and your backend returns JWT token. You use that token to connect the user. In the second case, the token is expired, and you need to refresh it (could be also the same REST API method from your backend, but not necessarily).
One question here which is usually an issue - your `NetworkingLayer` implementation is loading the token from your backend or hardcodes it locally? If the latter is true, this is only recommended while developing the app and shouldn't be used in production. Development tokens are described in the docs you've linked:
```swift
client.connectUser(userInfo: .init(id: "john-doe"), token: .development(userId: "john-doe"))
```
Hope this clarifies it for you. If not, I'm happy to answer any further questions.

2. I've spotted two things in the sample code. First, the token provider doesn't match our signature (`(@escaping (Result<Token, Error>) -> Void) -> Void`). Second, the closure passed in the closure has no way to escape. Either you can move it in a method, or even simpler, sth like this:
```swift
    public func setup(apiKey: String) {
        let config = ChatClientConfig(apiKey: .init(apiKey))
        ChatClient.shared = ChatClient(config: config) { [weak self] completion in
            self?.getChatToken() { result in
                completion(result)
            }
        }
    }
    
    func getChatToken(completion: @escaping (Result<Token, Error>) -> Void) {
        NetworkingLayer.getChatToken() { token in
            do {
                let token = try Token(rawValue: token)
                completion(.success(token))
            } catch {
                completion(.failure(error))
            }
        }
    }
```
3. You are actually reading the UIKit docs, not the one for SwiftUI. It might be confusing, since they are on the same page. We are working on splitting them on separate pages. The docs for what you are trying to achieve for SwiftUI are located here: https://getstream.io/chat/docs/sdk/ios/swiftui/components/message-reactions/#customizing-the-reactions-overlay-view, specifically the `supportedMessageActions`. You can for example load all the `MessageAction.defaultActions` in the method, and then iterate through those and apply your custom conditions. 

Hope this helps,
Martin

**Comment by JayMehta97** [comment]
Hi @martinmitrevski ,

Regarding the message actions even if I iterate through the `defaultActions` how can I check what MessageAction is delete and what MessageAction is reply. The only way to do that which I can think of is comparing their `title` which feels risky as their title can change in future and shoudn't be something to rely on. Can you let me know if I have understood something wrong here?

Thanks,
Jay

**Comment by martinmitrevski** [comment]
Hey @JayMehta97,

Yes, you are right, the comparison check was missing in the SDK and `title` is definitely not a reliable way to check. 

However, we've fixed this in our latest changes on `main` and we exposed a stable identifier for the message actions. Its values are the following:
```swift
public enum MessageActionId {
    public static let copy = "copy_message_action"
    public static let reply = "reply_message_action"
    public static let threadReply = "thread_message_action"
    public static let edit = "edit_message_action"
    public static let delete = "delete_message_action"
    public static let mute = "mute_message_action"
    public static let unmute = "unmute_message_action"
    public static let flag = "flag_message_action"
    public static let pin = "pin_message_action"
    public static let unpin = "unpin_message_action"
    public static let resend = "resend_message_action"
}

```

**Comment by martinmitrevski** [comment]
@JayMehta97 awesome! Btw, if you don't mind, I would like to close this issue. If you have additional issues/questions, it would be best to open separate issues, since others encountering similar issues can easily find the answer. This particular issue already has other useful questions that can be relevant to others.
Is that ok with you?

**Comment by JayMehta97** [comment]
Hey @martinmitrevski, sure, the original question and many related ones are resolved. Will open new issue for further queries. Thanks for all the help.
