### ISSUE TITLE
Horizontal Message alignment

### ISSUE THREAD

**Issue by borut-t** [GetStream/stream-chat-swiftui#382]
## What are you trying to achieve?
I want to show each message aligned to the left edge of the screen (Slack style). Currently it is auto aligned, right for my messages, left for incoming messages.

## If possible, how can you achieve this currently?
Not sure if this is possible.

## What would be the better way?
To support alignment customization with values [left, right, automatic]

## GetStream Environment
**GetStream Chat version:** 4.39
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.x
**Swift version:** 5.9
**Xcode version:** 15
**Device:** iPhone

**Comment by martinmitrevski** [comment]
Hey @borut-t,

Thanks for reporting this. One way to have this with the current versions of the SDK is to implement your own `makeMessageContainerView`, while reusing our building blocks.

However, since that might be too much work on integration side, and to be aligned with our UIKit SDK, we will also expose that soon as a config.

Best, Martin

**Comment by martinmitrevski** [comment]
hey @borut-t, this is now available on our `main` branch, it will be included in the next release.
Usage:
```swift
let utils = Utils(
    messageListConfig: MessageListConfig(messageListAlignment: .leftAligned)
)
let streamChat = StreamChat(chatClient: chatClient, utils: utils)
```
Best, Martin

**Comment by borut-t** [comment]
That's awesome. That is the quickest team ever 🙌
