### ISSUE TITLE
Problem with NavBar background colors in ChatChannel

### ISSUE THREAD

**Issue by fceldeiro** [GetStream/stream-chat-swiftui#432]
## What did you do?
While using the chatChannel in dark mode using a NavigationStack i noticed the following issue.
When scrolling down to the last message (even when having messages below the navBar) the color changes is it there were no content behind it.

## What did you expect to happen?
Navigation background color behavior should be more consistent.

## What happened instead?

No content
![Screenshot 2024-02-13 at 11 46 37](https://github.com/GetStream/stream-chat-swiftui/assets/1914557/213f0cc8-1938-4e0c-bbb1-35cd27d5ac01)

With content but i've scrolled to top (and background is changing)
![Screenshot 2024-02-13 at 11 47 17](https://github.com/GetStream/stream-chat-swiftui/assets/1914557/0a8f1c4e-e0df-41f4-b4d7-6e128c242dc5)

Scrolled to the last message and now background changed again.
![Screenshot 2024-02-13 at 11 47 52](https://github.com/GetStream/stream-chat-swiftui/assets/1914557/9ee87ef5-5c4f-4a7f-9ee9-e174caa6a138)

## GetStream Environment
**GetStream Chat frameworks:** StreamChatSwiftUI 4.48.0
**iOS version:** 17.2
**Swift version:** 5
**Xcode version:** 15.2
**Device:** Simulator 17.2 iPhone 15.pro

**Comment by martinmitrevski** [comment]
Hi @fceldeiro,

The expected behaviour is like the default nav bar behaviour - the background becomes translucent when there's content behind it. I'm attaching a video on how this works at the moment.

https://github.com/GetStream/stream-chat-swiftui/assets/2971717/9658cfdc-21a5-4e25-8c09-bfe086b09d67

Can you please share some more details about your app and how you use Stream's components? Also, any customizations of the tint / accent color you are doing will be helpful to reproduce this on our side.

Best, Martin

**Comment by martinmitrevski** [comment]
Thanks for the clarification, I see what you mean. In this case, that's kind of expected, because the chat view is an inverted list, both technically and conceptually. When you are at the bottom, you actually don't have new messages (no new content), when you go up, you load older ones.
