### ISSUE TITLE
Weird/jumping layout issue when scrolling on 

### ISSUE THREAD

**Issue by hyouuu** [GetStream/stream-chat-swiftui#457]
## What did you do?

We supplied customized message container view to `makeMessageContainerView`, but scrolling across several of them cause some of the newly appearing ones to appear near the center of the screen first then jump to the top of the screen

## What did you expect to happen?

No jumping layout issue

## What happened instead?

Jumping layout issue

## GetStream Environment
**GetStream Chat version:** commit "3bf3307d0aab92b1b1808f60957ce311040b4c4e") // waiting for https://github.com/GetStream/stream-chat-swiftui/pull/430 to merge
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.3.1
**Swift version:** 5.9
**Xcode version:** 15.2
**Device:** iPhone 14 Pro

## Additional context

https://github.com/GetStream/stream-chat-swiftui/assets/5061867/ee2cf974-2be3-4639-8e2e-39a2395b1d4b

**Comment by martinmitrevski** [comment]
Hi @hyouuu,

Since this is in a fork of yours, it's hard to tell where's the issue. It depends on what you are doing in your custom modifier, so you should narrow your investigation there.

We don't plan to merge the mentioned PR (it's already closed for a long time), since it doesn't fit our product.

Best, Martin
