### ISSUE TITLE
Apple rejected app because of permissions description

### ISSUE THREAD

**Issue by bobakemamian** [GetStream/stream-chat-swiftui#558]
## What did you do?
I submitted my app to apple and they rejected it because of the generic permissions descriptions:
![Screenshot-0725-120514](https://github.com/user-attachments/assets/1caaa6df-f520-423a-a1ed-a1e8b486f9f6)
![Screenshot-0725-120510](https://github.com/user-attachments/assets/f9b20cb1-76a9-4013-b3e3-4da560a568b2)

After getting rejected, I followed the instructions and added to my target and info the following:
![CleanShot 2024-07-25 at 15 59 17@2x](https://github.com/user-attachments/assets/03a237ac-66ad-4931-9e11-9f3810f36a26)
![CleanShot 2024-07-25 at 15 58 27@2x](https://github.com/user-attachments/assets/5236ba51-b7bc-4c31-ac5b-a163883cc72c)

## What did you expect to happen?
I expected the descriptions to appear in the permission dialogue.

## What happened instead?
It still shows up as this:
![Simulator Screenshot - iPhone 15 Pro - 2024-07-25 at 15 58 59](https://github.com/user-attachments/assets/89a7f970-e927-4e75-804d-e5702ad50722)

## GetStream Environment
**GetStream Chat version:** 4.59.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.5
**Swift version:**
**Xcode version:** 15.4
**Device:**

**Comment by martinmitrevski** [comment]
Hi @bobakemamian,

We don't have such strings in our SDK. We also don't bundle texts about permissions, it's the app's responsibility to do that.

Seems like you already had some texts for the permissions - otherwise you won't be able to open the camera. Best to search for these strings in your project, since they should be there for sure.

Hope that helps,
Martin

**Comment by bobakemamian** [comment]
Yeah my bad! Found it and works now.
