### ISSUE TITLE
Create new public func for `MessageAuthorAndDateView`

### ISSUE THREAD

**Issue by GeorgeVashakidze** [GetStream/stream-chat-swiftui#61]
## What are you trying to achieve?
We would like to have a new function under ViewFactory which can override `MessageAuthorAndDateView` and return custom view instead

<img width="250" alt="Screenshot 2022-05-09 at 09 23 24" src="https://user-images.githubusercontent.com/5709365/167345619-dc7c846e-43e3-4a1e-b589-73e7af324c7d.png">

**Comment by martinmitrevski** [comment]
Hey @GeorgeVashakidze,

This is now enabled on `main`. There are two methods:
```swift
func makeMessageDateView(for message: ChatMessage) -> some View
func makeMessageAuthorAndDateView(for message: ChatMessage) -> some View
```
The first one is used when only the date is displayed (e.g. current user and other user in direct channels).
The second one is used when both the author and date are displayed (other users in groups). 
You can of course change this logic since the message is passed as a parameter.

Hope this helps, 
Martin

**Comment by GeorgeVashakidze** [comment]
@martinmitrevski thanks a lot man. What a fast response. I like it.
Thank you

**Comment by martinmitrevski** [comment]
Awesome, glad it helps @GeorgeVashakidze.
