### ISSUE TITLE
Collapse group chat join/leave notifications

### ISSUE THREAD

**Issue by f3dm76** [GetStream/stream-chat-swiftui#668]
## What are you trying to achieve?
I want to group or at least hide "NAME joined the group" system messages, because there are too many.

## If possible, how can you achieve this currently?
I tried using
```
func makeSystemMessageView(message: ChatMessage) -> some View {
   EmptyView()
}
```
But there is still a padding forced on them:
![Simulator Screenshot - iPhone 16 Pro Max - 2024-11-27 at 12 39 10](https://github.com/user-attachments/assets/af5b8216-eec6-449b-8f0a-037cbe6d332e)
![Simulator Screenshot - iPhone 16 Pro Max - 2024-11-27 at 12 37 14](https://github.com/user-attachments/assets/84752ed6-8a51-4758-8add-2d392dd624f5)

## What would be the better way?
Could you group them on your end, like this?
```
Bobak & 20 others joined (if you tap it then you expand it) -> when you refresh the view it's minimized (whatever is easiest way to do it)

two or more collapse (example for join):
2 = bobak & eric joined
3 = bobak, eric, and oyku joined
4+ = bobak & 3 others joined

two or more collapse (example for joined & left):
2 = bobak joined & eric left
3 = bobak joined
4+ = bobak & 3 others joined
ana joined & bobak left
```
## GetStream Environment
GetStream Chat version: 4.67.0
GetStream Chat frameworks: StreamChat, StreamChatUI
iOS version: 18.0
Swift version: 6.0
Xcode version: 16.0
Device: sim iPhone 16 pro max

**Comment by nuno-vieira** [comment]
Hi @f3dm76,

I can't see the images, can you fix the URL?

Thank you!

**Comment by f3dm76** [comment]
@nuno-vieira, sorry about that, here are the normal images

**Comment by nuno-vieira** [comment]
Hi @f3dm76,

We do not support this, and we don't have any plans to support it at the moment. You might be able to make it work with negative paddings, but we do not recommend doing this at the UI level. In some rare scenarios, for example, if you only have system messages in a channel, you can potentially break pagination. So, in order to properly implement this, it would require filtering the message from the backend side. 

We recommend to conact our support here https://getstream.io/contact/support/ and request this feature. You will then be notified when we start working on it. 

Best,
Nuno
