### ISSUE TITLE
Links presented as plain text

### ISSUE THREAD

**Issue by zrxq** [GetStream/stream-chat-swiftui#98]
## What did you do?

Built the demo app, started a conversation, typed "Isnotspam.com", tapped send button. Then typed "Here's a link.com", tapped send button.

## What did you expect to happen?

Link attachments containing link titles and OG pictures where available.

## What happened instead?

Links are presented as plaintext.

## Additional context

I tried to entering Google.com. The link didn't expand. Then I entered "google.com". Suddenly the initial capital letter Google.com expanded, but the following lowercase still looked plain text.

**Comment by zrxq** [comment]
Here are some screenshots in case you need them. 

<img width="502" alt="Screenshot 2022-06-07 at 13 19 38" src="https://user-images.githubusercontent.com/820120/172359787-17afdc17-523c-4c4d-b9f0-78bfe42f4edc.png">

![Simulator Screen Shot - iPhone 12 Pro - 2022-06-07 at 13 22 52](https://user-images.githubusercontent.com/820120/172359806-72735213-2197-4d98-b6b7-8252b1c3f8fc.png)

**Comment by martinmitrevski** [comment]
Hey @zrxq,

Thanks for reporting this. It was indeed a bug in the SDK. This is now fixed and available on `main`.

This will work for things like google.com or other valid links. The ones like "link.com" still won't work, since this domain is not active and available for sale (basically our backend tells us what's a valid link and provides it as a link attachment).

Best,
Martin

**Comment by zrxq** [comment]
Thank you!
